enum EventCode{
  unlockNewLevel,
  updateRemoveFailNum,
  updateTimeNum,
  updateCoinNum,
  updatePayType,
  updateHeartNum,
  showNewUserWordsGuide,
  updateWheelNum,
  showWordChild,
  answerRight,
  showWordsGuideFromOther,
  oldUserShowBubbleGuide,
  oldUserShowWordsGuide,
  signSuccess,
  showMoneyLottie,
  showWithdrawChild,
}