name: plugin_base
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  get: 4.6.6
  flutter_screenutil: 5.9.0
  webview_flutter: 4.7.0
  event_bus: 2.0.0
  get_storage: 2.1.1
  flutter_staggered_grid_view: 0.4.1
  fluttertoast: 8.0.9
  #  assets_audio_player: 3.1.1
  flutter_tba_info: 0.0.7
  flutter_check_adjust_cloak: 0.2.8
  flutter_max_ad: 0.3.2
#  flutter_max_ad:
#    path: /Users/jaydenniked/StudioProjects/flutter_max_ad-0.3.1
  lottie: 2.6.0
  marquee: 2.2.3
  app_tracking_transparency: 2.0.5
  url_launcher: 6.3.0
  #  connectivity_plus: 6.0.3
  flutter_app_lifecycle: 0.0.1
  decimal: 3.0.2
#  permission_handler: 11.3.1
  intl: 0.19.0
#  flutter_foreground_task: 8.8.1+1
  firebase_messaging: 15.0.4
  flutter_workmanager_notification:
    path: /Users/jaydenniked/StudioProjects/flutter_workmanager_notification


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.plugin_base
        pluginClass: PluginBasePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
